[package]
name = "icon_scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
reqwest = "0.11.26"
thirtyfour = "0.31.0"
tokio = { version = "1.36.0", features = ["full"] }


